// @vitest-environment node
import { randomUUID } from "node:crypto";
import { afterEach, expect, it, vi } from "vitest";
import { configureEmailDatabaseForTests, closeEmailDatabaseForTests, ensureEmailDatabase, getEmailClient } from "@/lib/email/database";
import { migrateNotificationTelegramSchema } from "@/lib/email/notification-telegram-schema";
afterEach(()=>{vi.restoreAllMocks();closeEmailDatabaseForTests();});
async function fixture(){configureEmailDatabaseForTests("file:./telegram-schema-"+randomUUID()+".sqlite");await ensureEmailDatabase();const client=getEmailClient();await client.execute("DROP INDEX notification_telegram_destination");await client.execute("ALTER TABLE notification_devices DROP COLUMN telegram_binding_fingerprint");await client.execute("PRAGMA user_version=7");return client;}
it("adds schema8 atomically, preserves prior records and never lowers future schema",async()=>{
 const client=await fixture();await client.execute("CREATE TABLE synthetic_evidence (id TEXT PRIMARY KEY)");await client.execute("INSERT INTO synthetic_evidence VALUES ('preserved')");await migrateNotificationTelegramSchema(client);expect((await client.execute("PRAGMA user_version")).rows[0].user_version).toBe(8);await migrateNotificationTelegramSchema(client);expect((await client.execute("SELECT * FROM synthetic_evidence")).rows).toEqual([{id:"preserved"}]);await client.execute("PRAGMA user_version=9");await migrateNotificationTelegramSchema(client);expect((await client.execute("PRAGMA user_version")).rows[0].user_version).toBe(9);
});
it("failed migration rolls back binding column and version together",async()=>{
 const client=await fixture(),transaction=client.transaction.bind(client);vi.spyOn(client,"transaction").mockImplementationOnce(async()=>{const tx=await transaction("write"),execute=tx.execute.bind(tx);vi.spyOn(tx,"execute").mockImplementation(async statement=>{if(statement==="PRAGMA user_version=8")throw new Error("Synthetic failure");return execute(statement);});return tx;});await expect(migrateNotificationTelegramSchema(client)).rejects.toThrow("Synthetic failure");expect((await client.execute("PRAGMA user_version")).rows[0].user_version).toBe(7);expect((await client.execute("PRAGMA table_info(notification_devices)")).rows.some(row=>row.name==="telegram_binding_fingerprint")).toBe(false);
});
import { migrateNotificationTelegramUpdatesSchema } from "@/lib/email/notification-telegram-updates-schema";
it("schema9 preserves schema8 binding and never downgrades future versions",async()=>{configureEmailDatabaseForTests("file:./telegram-schema9-"+randomUUID()+".sqlite");await ensureEmailDatabase();const client=getEmailClient();await client.execute("DROP TABLE notification_telegram_updates");await client.execute("DROP TABLE notification_telegram_poll_leases");await client.execute("PRAGMA user_version=8");await migrateNotificationTelegramUpdatesSchema(client);expect((await client.execute("PRAGMA user_version")).rows[0].user_version).toBe(9);expect((await client.execute("PRAGMA table_info(notification_devices)")).rows.some(row=>row.name==="telegram_binding_fingerprint")).toBe(true);await client.execute("PRAGMA user_version=10");await migrateNotificationTelegramUpdatesSchema(client);expect((await client.execute("PRAGMA user_version")).rows[0].user_version).toBe(10);});
it("schema9 failure rolls back both new tables and version",async()=>{configureEmailDatabaseForTests("file:./telegram-schema9-"+randomUUID()+".sqlite");await ensureEmailDatabase();const client=getEmailClient();await client.execute("DROP TABLE notification_telegram_updates");await client.execute("DROP TABLE notification_telegram_poll_leases");await client.execute("PRAGMA user_version=8");const transaction=client.transaction.bind(client);vi.spyOn(client,"transaction").mockImplementationOnce(async()=>{const tx=await transaction("write"),execute=tx.execute.bind(tx);vi.spyOn(tx,"execute").mockImplementation(async statement=>{if(statement==="PRAGMA user_version=9")throw new Error("Synthetic failure");return execute(statement);});return tx;});await expect(migrateNotificationTelegramUpdatesSchema(client)).rejects.toThrow("Synthetic failure");expect((await client.execute("PRAGMA user_version")).rows[0].user_version).toBe(8);expect((await client.execute("SELECT name FROM sqlite_master WHERE name IN ('notification_telegram_updates','notification_telegram_poll_leases')")).rows).toHaveLength(0);});
