"use client";
import {useEffect,useRef,useState} from "react";
import {api,post} from "./api";
import type {OwnerAccountChoice,OwnerResourceChoice} from "@/lib/email/agent-owner-catalogue";
import type {TaskFields,TaskRecord,ResourceMutation,OperationView} from "@/lib/email/agent-resource-types";
import styles from "./EzraMail.module.css";
type Snapshot={complete:true;tasks:TaskRecord[];fetchedAt:string};
type Challenge={connectionId:string;userCode:string;verificationUri:string;expiresAt:string};
const empty:TaskFields={title:"",body:"",importance:"normal",due:null,reminder:null};
export function TodoView(){
 const [accounts,setAccounts]=useState<OwnerAccountChoice[]>([]),[accountId,setAccountId]=useState(""),[lists,setLists]=useState<OwnerResourceChoice[]>([]),[listId,setListId]=useState(""),[snapshot,setSnapshot]=useState<Snapshot|null>(null);
 const [fields,setFields]=useState<TaskFields>(empty),[editing,setEditing]=useState<TaskRecord|null>(null),[prepared,setPrepared]=useState<{operation:OperationView;mutation:ResourceMutation}|null>(null),[result,setResult]=useState<OperationView|null>(null),[challenge,setChallenge]=useState<Challenge|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const generation=useRef(0);const selected=accounts.find(c=>c.account.accountId===accountId),target=lists.find(l=>l.target.id===listId)?.target;
 const stale=!!snapshot&&Date.now()-Date.parse(snapshot.fetchedAt)>300_000;
 useEffect(()=>{let active=true;api<{accounts:OwnerAccountChoice[]}>("/api/auth/agent-grants/resources").then(data=>{if(active)setAccounts(data.accounts.filter(c=>c.account.provider==="microsoft"));},()=>{if(active)setError("Personal To Do access could not be loaded.");});return()=>{active=false;generation.current++;};},[]);
 async function run(work:(current:number)=>Promise<void>){setBusy(true);setError("");const current=generation.current;try{await work(current);}catch{if(current===generation.current)setError("The request could not be verified. Refresh before reviewing another action.");}finally{if(current===generation.current)setBusy(false);}}
 function reset(){generation.current++;setPrepared(null);setResult(null);setEditing(null);setFields(empty);setSnapshot(null);setChallenge(null);setError("");}
 async function refresh(current:number){if(!target)return;const data=await post<Snapshot>("/api/todo",{target});if(current===generation.current){setSnapshot(data);setPrepared(null);}}
 async function prepare(mutation:ResourceMutation){await run(async current=>{const operation=await post<OperationView>("/api/todo/actions",{action:"prepare",mutation});if(current===generation.current){setPrepared({operation,mutation});setResult(null);}});}
 const change=(next:TaskFields)=>{setFields(next);setPrepared(null);};
 return <section className={styles.settingsContent} aria-label="Microsoft To Do"><h1>Microsoft To Do</h1><p>Personal provider tasks. Your local Today checklist remains separate.</p>
  {error&&<p role="alert">{error}</p>}
  <label>Personal account<select aria-label="Personal account" disabled={busy} value={accountId} onChange={e=>{reset();setAccountId(e.target.value);setLists([]);setListId("");}}><option value="">Select personal account</option>{accounts.map(a=><option key={a.account.accountId} value={a.account.accountId}>{a.account.expectedEmail}</option>)}</select></label>
  {selected&&<>{selected.unavailable.map(message=><p key={message}>{message}</p>)}
   {!selected.availableScopes.includes("tasks.read")?<><p>Continue to Microsoft to grant Tasks.ReadWrite for {selected.account.expectedEmail}. Existing mail and calendar access will be preserved.</p><button disabled={busy} onClick={()=>run(async current=>{const data=await post<{ok:boolean;result:Challenge}>("/api/email",{action:"connect_microsoft",email:selected.account.expectedEmail,access:"tasks"});if(!data.ok)throw new Error();if(current===generation.current)setChallenge(data.result);})}>Connect personal To Do</button></>:<button disabled={busy} onClick={()=>run(async current=>{const data=await post<{resources:OwnerResourceChoice[]}>("/api/auth/agent-grants/resources",{account:selected.account,kind:"task_list"});if(current===generation.current)setLists(data.resources);})}>Load task lists</button>}
   {challenge&&<div><p>Sign in as {selected.account.expectedEmail}. Code: <strong>{challenge.userCode}</strong></p><a href={challenge.verificationUri.startsWith("https://")?challenge.verificationUri:undefined} target="_blank" rel="noreferrer">Open Microsoft sign-in</a><button disabled={busy} onClick={()=>run(async current=>{const response=await post<{ok:boolean;result:{status?:string}}>("/api/email",{action:"complete_microsoft_auth",connectionId:challenge.connectionId});if(!response.ok||response.result.status==="pending")throw new Error();const data=await api<{accounts:OwnerAccountChoice[]}>("/api/auth/agent-grants/resources");if(current===generation.current){setAccounts(data.accounts.filter(a=>a.account.provider==="microsoft"));setChallenge(null);}})}>Check completed sign-in</button></div>}
  </>}
  {!!lists.length&&<><label>Task list<select aria-label="Task list" disabled={busy} value={listId} onChange={e=>{reset();setListId(e.target.value);}}><option value="">Select task list</option>{lists.map(list=><option key={list.target.id} value={list.target.id}>{list.title}</option>)}</select></label><button disabled={busy||!target} onClick={()=>run(refresh)}>Refresh tasks</button></>}
  {snapshot&&<><p>Read {snapshot.fetchedAt}</p>{stale&&<p role="status">This task snapshot is stale. Refresh before editing or completing.</p>}{snapshot.tasks.map(task=><article key={task.id}><h2>{task.title}</h2><p style={{whiteSpace:"pre-wrap"}}>{task.body}</p><p>{task.status} · {task.importance}</p>{task.due&&<p>Due {task.due.kind==="date"?task.due.date:task.due.instant} ({task.due.timezone})</p>}{task.reminder&&<p>Reminder {task.reminder.instant} ({task.reminder.timezone})</p>}<button disabled={busy||stale||task.recurring||!selected?.availableScopes.includes("tasks.update")} onClick={()=>{setEditing(task);setFields({title:task.title,body:task.body,importance:task.importance,due:task.due,reminder:task.reminder});setPrepared(null);}}>Edit task</button><button disabled={busy||stale||task.recurring||task.status==="completed"||!selected?.availableScopes.includes("tasks.complete")} onClick={()=>target&&prepare({kind:"tasks.complete",target:target as Extract<ResourceMutation,{kind:"tasks.complete"}>["target"],taskId:task.id,expectedRevision:task.revision})}>Review completion</button></article>)}</>}
  {target&&selected?.availableScopes.includes(editing?"tasks.update":"tasks.create")&&<fieldset disabled={busy}><legend>{editing?"Edit provider task":"New provider task"}</legend><label>Title<input aria-label="Task title" value={fields.title} onChange={e=>change({...fields,title:e.target.value})}/></label><label>Notes<textarea aria-label="Task notes" value={fields.body} onChange={e=>change({...fields,body:e.target.value})}/></label><label>Importance<select value={fields.importance} onChange={e=>change({...fields,importance:e.target.value as TaskFields["importance"]})}>{["low","normal","high"].map(value=><option key={value}>{value}</option>)}</select></label><label>Due date<input aria-label="Due date" type="date" value={fields.due?.kind==="date"?fields.due.date:""} onChange={e=>change({...fields,due:e.target.value?{kind:"date",date:e.target.value,timezone:"America/Chicago"}:null})}/></label><p>New date-only due dates use America/Chicago. An existing instant is preserved unless changed.</p><label>Reminder (UTC)<input aria-label="Reminder UTC" type="datetime-local" value={fields.reminder?new Date(fields.reminder.instant).toISOString().slice(0,16):""} onChange={e=>change({...fields,reminder:e.target.value?{instant:new Date(`${e.target.value}Z`).toISOString(),timezone:"UTC"}:null})}/></label><button disabled={!fields.title.trim()||!!editing&&stale} onClick={()=>{const list=target as Extract<ResourceMutation,{kind:"tasks.create"}>["target"];return prepare(editing?{kind:"tasks.update",target:list,taskId:editing.id,expectedRevision:editing.revision,patch:fields}:{kind:"tasks.create",target:list,fields});}}>Review task</button>{editing&&<button onClick={()=>{setEditing(null);setFields(empty);setPrepared(null);}}>Cancel edit</button>}</fieldset>}
  {prepared&&<section aria-label="Exact task review"><h2>Review {prepared.mutation.kind}</h2><p>{prepared.mutation.kind!=="calendar.create"&&prepared.mutation.target.account.expectedEmail} · {listId}</p><pre style={{whiteSpace:"pre-wrap",overflowWrap:"anywhere"}}>{JSON.stringify(prepared.mutation,null,2)}</pre><p>Prepared until {prepared.operation.expiresAt}</p><button disabled={busy} onClick={()=>run(async current=>{const view=await post<OperationView>("/api/todo/actions",{action:"execute",operationId:prepared.operation.id,payloadHash:prepared.operation.payloadHash});if(current===generation.current){setResult(view);setPrepared(null);if(view.status==="succeeded"){setEditing(null);setFields(empty);await refresh(current);}}})}>Confirm task action</button><button disabled={busy} onClick={()=>setPrepared(null)}>Cancel review</button></section>}
  {result&&<p role="status">Operation {result.id}: {result.status}{result.receipt?` · verified ${result.receipt.outcome}`:""}{result.status==="unknown"?". Outcome is uncertain; do not repeat this action.":""}</p>}
 </section>;
}
